

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: localhost 


development:
  <<: *default
  database: budgetmode_development

test:
  <<: *default
  database: budgetmode_test


production:
  <<: *default
  database: budgetmode_production
  
